# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b4b5633995ec6a8bde18ef02d6107ab6c77d17a711b380c8aceca10b03342ff3a9a11280c6ecc1380ffa1fd48e2fc4035e1b81dde73373c62a5ad0dbd98a4e8

test:
  secret_key_base: d025be9eed1374ea55e6737e9bb8eac68b21814fe7045889f30bdaa965b2f38568c784fea9d525c688755bf2616c10f32c64dac87af5d1a7f7d8994524ee3e18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
